name: Core Regulus Frontend Deploy
run-name: ${{ github.actor }} is deploying the project

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Personal Projects

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup docker volumes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          port: 22
          script: |
            docker system prune -a --volumes -f
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{secrets.SSH}}
          source: "*"
          target: "/home/ci/core-regulus/frontend"          
      - name: Docker Compose Node
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          port: 22
          script: |
            cd /home/ci/core-regulus/frontend/deploy
            docker compose build
            docker compose run -rm --workdir /app/server --remove-orphans --entrypoint npm node install
            docker compose run -rm --workdir /app/server --remove-orphans node deploy.js
